server:
  port : 8093
spring:
#  cloud:
#    gcp:
#      project-id: animal-shelter-351809
#      credentials:
#        location: animal-shelter-351809-479e56280414.json
      #          classpath: D:\MyProject\Website projects\Projects\animal_shelter_microservices\animals\src\main\resources\animal-shelter-351809-479e56280414.json
#      sql:
#        database-name: animals-db
#        instance-connection-name: animal-shelter-351809:us-central1:animal-db
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/animals
    username: root
    password: root
#    initialization-mode: always
  profile:
    active: mysql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
